config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'magic_ball' => "magic_ball#result"

  get 'guess_secret_number' => "secret_number#guess"

  post 'secret_number_results/:guess' => "secret_number#results", :as => "secret_number_results"

  get 'play_rps' => 'rps#play'
  post 'rps_result/:weapon' => 'rps#result', :as => "rps_result"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/magic_ball_controller.rb
class MagicBallController < ApplicationController

  def result
    @magic_answer = generate_random_response
    puts @magic_answer
  end

  private
  def generate_random_response
    all_responses = [
      "I guess so..",
      "Maybe. Just maybe.",
      "I'm not sure, maybe ask someone else",
      "Absolutely",
      "Answer Unclear Ask Later",
      "Cannot Foretell Now",
      "Can't Say Now",
      "Chances Aren't Good",
      "Consult Me Later",
      "Don't Bet On It",
      "Focus And Ask Again",
      "Indications Say Yes",
      "Looks Like Yes",
      "No",
      "No Doubt About It",
      "Positively",
      "Prospect Good",
      "So It Shall Be",
      "The Stars Say No",
      "Unlikely",
      "Very Likely", "Yes",
      "You Can Count On It"
    ]
    all_responses.sample #.sample selects a random element from the array and return it
  end

end

app/controllers/rps_controller.rb
class RpsController < ApplicationController

  def play
  end

  def result
    @user_weapon = params[:weapon]
    @server_weapon = generate_server_weapon
    @result = generate_results(@user_weapon, @server_weapon)
  end

  private
  def generate_server_weapon
    ["rock", "paper", "scissors"].sample
  end

  def generate_results(user_weapon, server_weapon)

    if user_weapon == server_weapon
      return "Draw"
    end

    winner_of = {
      "rock" => "paper",
      "paper" => "rock",
      "scissors" => "paper",

    }

    if winner_of[server_weapon] == user_weapon
      return "Win"
    else
      return "Lose"
    end

  end

end

app/controllers/secret_number_controller.rb
class SecretNumberController < ApplicationController

  def guess
  end

  def result
    @result = params[:guess].to_i == generate_secret_number
  end

  private
  def generate secret_number
    4
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamesOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/magic_ball/result.html.erb
<h1>The Magic 8 Ball...</h1>


<%= image_tag "spider.png" %>



<div class="container">
<%= form_tag('/magic_ball', method: :get) do %>
  <%= text_field_tag :question, nil, placeholder: "Ask me your question", class: 'question_class' %>
  <%= submit_tag "Ask" %>
<% end %>

<% if params[:question].present? %>
<p>
You asked: <%= params[:question] %>
</p>
<% end %>
</div>


<div class="shadow"></div>

<div class="epos">
<div class="eball">
  <div class="egrad"></div>
  <div class="ewin"><div>
  <div class="triangle"></div>
  <div class="textbox"><%= @magic_answer %></div>
</div>
</div>

app/views/rps/play.html.erb
<p>Choose!</p>

<%= link_to "Rock", rps_result_path(:weapon => "rock"), method: :post %>
<%= link_to "Paper", rps_result_path(:weapon => "paper"), method: :post %>
<%= link_to "Scissors", rps_result_path(:weapon => "scissors"), method: :post %>

app/views/rps/result.html.erb
<h1>Results</h1>
<p><%= @result %></p>

<p>You showed a <%= @user_weapon %></p>
<p>The computer chose <%= @server_weapon %></p>

  <%= link_to "Try Again", play_rps_path %>

app/views/secret_number/guess.html.erb
<h1>My guess is: </h1>


<% 11.times do |i| %>
  <%= link_to "Guess #{i}", secret_number_results_path(guess: i),
  method: :post %>

<% end %>

app/views/secret_number/result.html.erb
<p>Your guess was: <%= params[:guess] %></p>

<% if @result %>
<p>Good guess! You got it right!</p>

<% else %>

<p>Oh no... You guessed wrongly... </p>

<% end %>

<%= link_to "Back", guess_secret_number_path %>

app/views/static_pages/index.html.erb
<h1>Hello World!</h1>